chore: Remove lodash
netlify/gatsby-plugin-netlify pull request #130
Opened 2022-05-17 18:49 UTC by sarahetter

This removes (most) of the lodash we have in this repo. I kept `mergeWith` as there wasn't any simple ES6/quick fix I could write up to replace this function, so I opted to only include the `lodash.mergewith` package, instead of all of lodash.

2022-05-18 14:23 UTC, nickytonline requested changes
This is looking great @sarahetter! I l left some comments and change requests.

2022-05-18 20:09 UTC, sarahetter commented
Depends on https://github.com/netlify/gatsby-plugin-netlify/pull/132 to be merged first

2022-05-19 13:05 UTC, ericapisani approved these changes

2022-05-19 17:33 UTC, nickytonline approved these changes
Looks good, @sarahetter! There are so many `any`s in the codebase that the changes in this PR are fine. As discussed. we'll schedule cleaning up types in here at some point.

Also, as we discovered, `_.flow` was using `any` pretty liberally. 🙃

2022-05-19 17:34 UTC, merged